# Generated by Django 2.2.1 on 2019-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=1200),
        ),
    ]
