# Generated by Django 2.2.1 on 2019-10-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_auto_20191027_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volonteer',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
